version: "3"

services:
  app:
    restart: always
    container_name: conceal_guardian
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 16000:16000
    volumes:
      - .conceal:/root/.conceal

